---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sbballro/public_html/sbdcrobodj.com
    -  /bin/cp _.sbdcrobodj.com.pem.txt $DEPLOYPATH
    -  /bin/cp custom.html $DEPLOYPATH
    -  /bin/cp index.html $DEPLOYPATH
    -  /bin/cp index.js $DEPLOYPATH
    -  /bin/cp logo.png $DEPLOYPATH
    -  /bin/cp songlist.html $DEPLOYPATH
    -  /bin/cp -R css $DEPLOYPATH
    -  /bin/cp -R img $DEPLOYPATH
    -  /bin/cp -R js $DEPLOYPATH  
---
deployment:
  tasks:
   - export DEPLOYPATH=/home/sbballro/public_html/sbdcrobodj.com/music
    -  /bin/cp -R 2step $DEPLOYPATH
    -  /bin/cp -R amtango $DEPLOYPATH
    -  /bin/cp -R atango $DEPLOYPATH
    -  /bin/cp -R bachata $DEPLOYPATH
    -  /bin/cp -R bolero $DEPLOYPATH
    -  /bin/cp -R cbychacha $DEPLOYPATH
    -  /bin/cp -R chacha $DEPLOYPATH 
    -  /bin/cp -R ecs $DEPLOYPATH
    -  /bin/cp -R foxtrot $DEPLOYPATH
    -  /bin/cp -R hustle $DEPLOYPATH
    -  /bin/cp -R mambo $DEPLOYPATH
    -  /bin/cp -R merenque $DEPLOYPATH
    -  /bin/cp -R nc2 $DEPLOYPATH
    -  /bin/cp -R polka $DEPLOYPATH
    -  /bin/cp -R quickstep $DEPLOYPATH
    -  /bin/cp -R rumba $DEPLOYPATH
    -  /bin/cp -R salsa $DEPLOYPATH
    -  /bin/cp -R samba $DEPLOYPATH
    -  /bin/cp -R special $DEPLOYPATH
    -  /bin/cp -R vwaltz $DEPLOYPATH
    -  /bin/cp -R waltz $DEPLOYPATH
    -  /bin/cp -R wcs $DEPLOYPATH
    -  /bin/cp -R wpartner $DEPLOYPATH
    -  /bin/cp -R wwaltz $DEPLOYPATH
 