---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sbballro/public_html/sbdcrobodj.com
    -  /bin/cp _.sbdcrobodj.com.pem.txt $DEPLOYPATH
    -  /bin/cp custom.html $DEPLOYPATH
    -  /bin/cp index.html $DEPLOYPATH
    -  /bin/cp index.js $DEPLOYPATH
    -  /bin/cp logo.png $DEPLOYPATH
    -  /bin/cp songlist.html $DEPLOYPATH
    -  /bin/cp -R css $DEPLOYPATH
    -  /bin/cp -R img $DEPLOYPATH
    -  /bin/cp -R js $DEPLOYPATH
    - export DEPLOYPATH2=/home/sbballro/public_html/sbdcrobodj.com/music
    -  /bin/cp -R 2step $DEPLOYPATH2
    -  /bin/cp -R amtango $DEPLOYPATH2
    -  /bin/cp -R atango $DEPLOYPATH2
    -  /bin/cp -R bachata $DEPLOYPATH2
    -  /bin/cp -R bolero $DEPLOYPATH2
    -  /bin/cp -R cbychacha $DEPLOYPATH2
    -  /bin/cp -R chacha $DEPLOYPATH2 
    -  /bin/cp -R ecs $DEPLOYPATH2
    -  /bin/cp -R foxtrot $DEPLOYPATH2
    -  /bin/cp -R hustle $DEPLOYPATH2
    -  /bin/cp -R mambo $DEPLOYPATH2
    -  /bin/cp -R merenque $DEPLOYPATH2
    -  /bin/cp -R nc2 $DEPLOYPATH2
    -  /bin/cp -R polka $DEPLOYPATH2
    -  /bin/cp -R quickstep $DEPLOYPATH2
    -  /bin/cp -R rumba $DEPLOYPATH2
    -  /bin/cp -R salsa $DEPLOYPATH2
    -  /bin/cp -R samba $DEPLOYPATH2
    -  /bin/cp -R special $DEPLOYPATH2
    -  /bin/cp -R vwaltz $DEPLOYPATH2
    -  /bin/cp -R waltz $DEPLOYPATH2
    -  /bin/cp -R wcs $DEPLOYPATH2
    -  /bin/cp -R wpartner $DEPLOYPATH2
    -  /bin/cp -R wwaltz $DEPLOYPATH2
 